apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: byhb6fw1g-java-springboot
  janus-idp.io/tekton: byhb6fw1g-java-springboot
  backstage.io/kubernetes-id: byhb6fw1g-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: byhb6fw1g-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
